export const CHAR_INFO = [
	{
		titleKey: 'knight',
		descKey: 'knightDesc',
		model: '/img/eternal-models/knight.glb',
		attributes: {
			Vitality: 12,
			Strength: 7,
			Dexterity: 15,
			Intelligence: 6,
			Mentality: 13,
			Luck: 4,
			Charisma: 12,
		},
	},
	{
		titleKey: 'paladin',
		descKey: 'paladinDesc',
		model: '/img/eternal-models/paladin.glb',
		attributes: {
			Vitality: 16,
			Strength: 12,
			Dexterity: 9,
			Intelligence: 4,
			Mentality: 10,
			Luck: 9,
			Charisma: 7,
		},
	},
	{
		titleKey: 'necromancer',
		descKey: 'necromancerDesc',
		model: '/img/eternal-models/necromancer.glb',
		attributes: {
			Vitality: 7,
			Strength: 5,
			Dexterity: 14,
			Intelligence: 20,
			Mentality: 6,
			Luck: 1,
			Charisma: 3,
		},
	},
	{
		titleKey: 'gladiator',
		descKey: 'gladiatorDesc',
		model: '/img/eternal-models/gladiator.glb',
		attributes: {
			Vitality: 12,
			Strength: 10,
			Dexterity: 14,
			Intelligence: 3,
			Mentality: 15,
			Luck: 1,
			Charisma: 12,
		},
	},
	{
		titleKey: 'berserker',
		descKey: 'berserkerDesc',
		model: '/img/eternal-models/berserker.glb',
		attributes: {
			Vitality: 16,
			Strength: 14,
			Dexterity: 3,
			Intelligence: 2,
			Mentality: 12,
			Luck: 5,
			Charisma: 4,
		},
	},
	{
		titleKey: 'assassin',
		descKey: 'assassinDesc',
		model: '/img/eternal-models/assassin.glb',
		attributes: {
			Vitality: 11,
			Strength: 9,
			Dexterity: 16,
			Intelligence: 14,
			Mentality: 9,
			Luck: 14,
			Charisma: 5,
		},
	},
	{
		titleKey: 'hunter',
		descKey: 'hunterDesc',
		model: '/img/eternal-models/hunter.glb',
		attributes: {
			Vitality: 8,
			Strength: 7,
			Dexterity: 14,
			Intelligence: 13,
			Mentality: 9,
			Luck: 11,
			Charisma: 6,
		},
	},
]
